# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [2]:
s="Hi there sam!"
t=s.split()
print(t)

['Hi', 'there', 'sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [4]:
planet="Earth"
diameter=12742
print("the diameter of {} is {} kilometers.".format(planet,diameter))

the diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [21]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]


'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [5]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
import numpy as np
array=np.ones(10)*5
print("an array of ten fives:")
print(array)

an array of ten fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [7]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array) 

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
import numpy as np
t=np.arange(0,9).reshape(3,3)
print(t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7.  a and b Concatinate
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b),axis=0)
c


array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [12]:
import pandas as pd
data=[['mathi',26],['uma',30],['malini',25]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df
  



Name  Age
0   mathi   26
1     uma   30
2  malini   25

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [15]:
dates=pd.date_range('1/1/2023','10/2/2023')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [19]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
dt=zip(lists)
df=pd.DataFrame(dt,columns=["d"])
print(type(df))
print(df)

<class 'pandas.core.frame.DataFrame'>
              d
0  [1, aaa, 22]
1  [2, bbb, 25]
2  [3, ccc, 24]
